[package]
name = "vec-string"
version = "0.2.1"
edition = "2021"
authors = ["Cody Bloemhard <codybloemhard@gmail.com> + Utishnik"]
description = "To print Vec<Display>."
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/Utishnik/vec-string"
keywords = ["vec","string"]
categories = ["util"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambassador = "0.5.1"
rayon = { version = "1.10", optional = true }
orx-parallel = { version = "3", optional = true }
itertools = { version = "0.14", optional = true }
itermore = { version = "0.8", optional = true, features = ["full"] }

[features]
default = ["std","rayon","orx_parallel","itertools","itermore","dyn_async","impl_async","ambassador_delegatable"]
std = []
rayon = ["dep:rayon"]
orx_parallel = ["dep:orx-parallel"]
itertools = ["dep:itertools"]
itermore = ["dep:itermore"]
dyn_async = []
impl_async = []
ambassador_delegatable = []

[dev-dependencies]
pollster = "1.0.1"
